"""Module for generating diagrams."""
# pylint: disable=duplicate-code,wrong-import-position
# pylint: disable=line-too-long,import-outside-toplevel,missing-function-docstring
import json
import os


def generate_dependency_graph(graph):
    """Generates a Mermaid graph for internal modules and their imports."""
    mermaid = ["```mermaid", "graph TD"]

    # We'll map file paths to simple node names
    nodes = {}
    for i, filepath in enumerate(graph.get("files", {}).keys()):
        node_id = f"F{i}"
        nodes[filepath] = node_id
        # Use filename as label, allow clicking to source
        filename = os.path.basename(filepath)
        mermaid.append(f'    {node_id}["{filename}"]')
        # Click event mapping for github
        mermaid.append(f'    click {node_id} "{filepath}" "Go to source"')

    for filepath, info in graph.get("files", {}).items():
        node_id = nodes.get(filepath)
        if not node_id:
            continue

        for imp in info.get("imports", []):
            # Check if this import matches an internal file roughly
            target_node = None
            for p, n_id in nodes.items():
                if imp in p:
                    target_node = n_id
                    break

            if target_node and target_node != node_id:
                mermaid.append(f"    {node_id} -->|imports| {target_node}")

    mermaid.append("```")
    return "\n".join(mermaid)


def generate_api_flow(graph):
    """Generates a Mermaid flow diagram for API endpoints."""
    mermaid = ["```mermaid", "sequenceDiagram", "    participant Client"]

    # Check if we have app.py as server
    has_server = "app.py" in [
        os.path.basename(f) for f in graph.get("files", {}).keys()
    ]
    if has_server:
        mermaid.append("    participant Server")

    for endpoint in graph.get("api_endpoints", []):
        method = endpoint.get("method", "GET")
        path = endpoint.get("path", "/")
        func = endpoint.get("function", "handler")
        mermaid.append(f"    Client->>Server: {method} {path}")
        mermaid.append(f"    Server-->>Client: calls {func}()")

    mermaid.append("```")
    return "\n".join(mermaid)


def generate_system_architecture(graph):
    """Generates a high-level system architecture Mermaid diagram."""
    mermaid = ["```mermaid", "graph LR"]

    mermaid.append("    subgraph External Dependencies")
    for i, ext in enumerate(graph.get("external_deps", [])[:10]):  # Limit to top 10
        mermaid.append(f'        E{i}["{ext}"]')
    mermaid.append("    end")

    mermaid.append("    subgraph Core System")
    if "FastAPI" in graph.get("frameworks", []):
        mermaid.append('        API["FastAPI App"]')
    else:
        mermaid.append('        App["Main Application"]')

    if "Streamlit" in graph.get("frameworks", []):
        mermaid.append('        UI["Streamlit Frontend"]')
    mermaid.append("    end")

    if "FastAPI" in graph.get("frameworks", []) and "Streamlit" in graph.get(
        "frameworks", []
    ):
        mermaid.append("    UI -->|HTTP Requests| API")

    mermaid.append("```")
    return "\n".join(mermaid)


def main():
    try:
        with open("docs/knowledge_graph.json", "r", encoding="utf-8") as f:
            graph = json.load(f)
    except Exception as e:  # pylint: disable=broad-exception-caught
        print(f"Error loading graph: {e}")
        return

    content = []
    content.append("# Repository Architecture\n")
    content.append("*Auto-generated by CI/CD Pipeline*\n")

    content.append("## System Architecture\n")
    content.append(generate_system_architecture(graph))
    content.append("\n")

    content.append("## Internal Dependency Graph\n")
    content.append(generate_dependency_graph(graph))
    content.append("\n")

    if graph.get("api_endpoints"):
        content.append("## API Endpoints\n")
        content.append(generate_api_flow(graph))
        content.append("\n")

    with open("docs/architecture.md", "w", encoding="utf-8") as f:
        f.write("\n".join(content))

    print("Generated diagrams to docs/architecture.md")


if __name__ == "__main__":
    main()
# pylint: disable=duplicate-code
