sonar.exclusions=vulture_whitelist.py
sonar.issue.ignore.multicriteria=vulture
sonar.issue.ignore.multicriteria.vulture.ruleKey=*
sonar.issue.ignore.multicriteria.vulture.resourceKey=vulture_whitelist.py
