sonar.projectKey=NITISH-R-G_rag-context-optimizer
sonar.organization=nitish-r-g
sonar.python.version=3.11
sonar.sources=env,server,app.py,streamlit_app.py
sonar.tests=tests
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=*
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*vulture_whitelist.py
